services:
  redis-data-protection:
    image: redis:alpine3.21
    container_name: tms-redis-data-protection
    restart: "no"
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    entrypoint: ["redis-server"]
    command: >
      /usr/local/etc/redis/redis.conf --maxmemory-policy noeviction --appendonly yes --requirepass ${REDIS_PWD} --masterauth ${REDIS_PWD}
  
  redis-session-cache:
    image:  redis:alpine3.21
    container_name: tms-redis-session-cache
    restart: "no"
    ports:
      - "6380:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    entrypoint: ["redis-server"]
    command: >
      /usr/local/etc/redis/redis.conf --maxmemory-policy allkeys-lru --appendonly no --requirepass ${REDIS_PWD} --masterauth ${REDIS_PWD}
  
  HashiCorp-Vault:
    image: hashicorp/vault:latest
    container_name: tms-vault
    restart: "no"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
    entrypoint: ["/bin/sh", "-c", "chmod +x /usr/local/bin/entrypoint.sh && /usr/local/bin/entrypoint.sh"]

  SqlServer:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: DevServer
    hostname: DevServer
    restart: "unless-stopped"
    networks:
      - tms_network
    ports:
      - "1433:1433"
    environment:
      MSSQL_mssql_pwd: ${MSSQL_PWD}
      ACCEPT_EULA: "Y"
      TZ: "Europe/London"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL",  "grep -q 'SQL Server is now ready for client connections. This is an informational message; no user action is required.' /var/opt/mssql/log/errorlog || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 12

  keycloak:
    image: keycloak/keycloak:latest
    container_name: tms-keycloak
    restart: no
    networks:
      - tms_network
    ports:
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: mssql
      KC_DB_URL: "jdbc:sqlserver://DevServer:1433;databaseName=keycloak;trustServerCertificate=true"
      KC_DB_USERNAME: ${MSSQL_USER}
      KC_DB_PASSWORD: ${MSSQL_PWD}
      KC_DB_SCHEMA: dbo
      KC_PROXY: edge
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT_HTTPS: true
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/tls.key
      KC_HTTP_ENABLED: false
      KC_HTTPS_PORT: 8443
      KC_DB_POOL_INITIAL_SIZE: 5
      KC_DB_POOL_MIN_SIZE: 5
      KC_DB_POOL_MAX_SIZE: 100
      KC_PROXY_ADDRESS_FORWARDING: false
      KC_CACHE: local
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_LOG_LEVEL: INFO
      KC_LOG_CONSOLE_OUTPUT: default
      KC_FEATURES:
      KC_TRANSACTION_XA_ENABLED: false
    volumes:
     - ./maui_realm.json:/opt/keycloak/data/import/maui_realm.json
     - ./certs:/opt/keycloak/conf
    command: ["start-dev", "--import-realm"]
    depends_on:
      SqlServer:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 12

networks:
  tms_network:
    name: tms_network
    external: true
    
volumes:
  mssql_data:
    name: mssql_data
    external: true
  keycloak_themes:
    name: keycloak_themes
    external: true
  keycloak_data:
    name: keycloak_data
    external: true

