services:
  redis-data-protection:
    image: redis:8.0-M03
    container_name: tms-redis-data-protection
    restart: "no"
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    entrypoint: ["redis-server"]
    command: >
      /usr/local/etc/redis/redis.conf --maxmemory-policy noeviction --appendonly yes --requirepass ${REDIS_PWD} --masterauth ${REDIS_PWD}
  
  redis-session-cache:
    image:  redis:8.0-M03
    container_name: tms-redis-session-cache
    restart: "no"
    ports:
      - "6380:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    entrypoint: ["redis-server"]
    command: >
      /usr/local/etc/redis/redis.conf --maxmemory-policy allkeys-lru --appendonly no --requirepass ${REDIS_PWD} --masterauth ${REDIS_PWD}
  
  HashiCorp-Vault:
    image: hashicorp/vault:latest
    container_name: tms-vault
    restart: "no"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
    entrypoint: ["/bin/sh", "-c", "chmod +x /usr/local/bin/entrypoint.sh && /usr/local/bin/entrypoint.sh"]
    
  SqlServer:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: DevServer
    hostname: DevServer
    restart: "unless-stopped"
    networks:
      - tms_network
    ports:
      - "1433:1433"
    environment:
      MSSQL_mssql_pwd: ${MSSQL_PWD}
      ACCEPT_EULA: "Y"
      TZ: "Europe/London"
    volumes:
      - mssql_data:/var/opt/mssql

networks:
  tms_network:
    name: tms_network
    
volumes:
  mssql_data:
    name: mssql_data
    external: true
